name: Download and process artifact size metrics
description: TODO

inputs:
  download:
    description: TODO
    default: "false"
    # TODO: Additional inputs

runs:
  using: composite
  steps:
    - name: Download and process artifact size metrics
      shell: bash
      run: |
        chmod +x ./src/main.sh
        chmod +x ./src/s3.sh
        chmod +x ./src/compare.sh
        chmod +x ./src/comment.sh
        
        ./src/main.sh

    - name: Post artifact analysis comment # TODO: MOVE TO SCRIPT IF POSSIBLE
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('node:fs')
          const prNumber = context.issue.number ?? process.env.SDK_PR # TOSO - CHANGE - THIS WON'T WORK FOR EXTERNAL CONTRIBUTORS BTW - IF EXTERNAL CONTRIBUTOR JUST FAIL
          const prInfo = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          })

          const hasAcknowledgeLabel = prInfo.data.labels.some(label => label.name === 'acknowledge-artifact-size-increase')

          const getComments = `
            query { 
              repository(owner:"${context.repo.owner}", name:"${context.repo.repo}"){
                pullRequest(number: ${prNumber}) {
                  id
                  comments(last:100) {
                    nodes {
                      id
                      body
                      author {
                        login
                      }
                      isMinimized
                    }
                  }
                }
              }
            }`

          const response = await github.graphql(getComments)
          const comments = response.repository.pullRequest.comments.nodes

          // Minimize outdated artifact-size comments
          const mutations = comments
            .filter(comment => comment.author.login == 'github-actions' && !comment.isMinimized && comment.body.startsWith('Affected Artifacts'))
            .map(comment =>
              github.graphql(`mutation {
                minimizeComment(input:{subjectId:"${comment.id}", classifier:OUTDATED}){
                  clientMutationId
                }
              }`)
            )
          await Promise.all(mutations)

          const comment = fs.readFileSync('build/reports/metrics/artifact-analysis.md', 'utf8')

          // Create a new comment with the latest artifact analysis
          const writeComment = `mutation {
            addComment(input:{body:"""${comment}""", subjectId:"${response.repository.pullRequest.id}"}){
              commentEdge {
                node {
                  id
                }
              }
            }}`
          const addCommentResponse = await github.graphql(writeComment)
          const newCommentId = addCommentResponse.addComment.commentEdge.node.id

          // Minimize the newly-created comment if artifact size increase is acknowledged
          if (hasAcknowledgeLabel) {
            await github.graphql(`mutation {
              minimizeComment(input:{subjectId:"${newCommentId}", classifier:RESOLVED}){
                clientMutationId
              }
            }`)
          }

    - name: Fail if large size increase
      shell: bash
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'acknowledge-artifact-size-increase') }}
      run: |
        if [ "$LARGE_DIFF" == "true" ]; then
            echo An artifact increased in size by more than allowed or a new artifact was created.
            echo If this is expected please add the 'acknowledge-artifact-size-increase' label to this pull request.
            exit 1
        fi
