# TODO: Delete this action when we migrate off JReleaser for all our releases

name: JReleaser check
description: Smoke test that checks our jreleaser release command works
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Gradle
      uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main

    - name: Test jreleaserFullRelease
      shell: bash
      run: |
        export JRELEASER_PROJECT_JAVA_GROUP_ID="com.sonatype.central.testing.amazon"
        export JRELEASER_MAVENCENTRAL_USERNAME="foo"
        export JRELEASER_MAVENCENTRAL_TOKEN="foo"
        export JRELEASER_GENERIC_TOKEN="foo"

        ./gradlew jreleaserFullRelease --dryrun --stacktrace
