name: Extract version from libs.versions.toml
description: Extracts the specified version from a libs.versions.toml file

inputs:
  working-directory:
    description: The directory in which to run the action
    default: .
  version-name:
    description: The name of the version to extract e.g. 'crt-kotlin-version'

runs:
  using: composite
  steps:
    - name: Extract version
      shell: bash
      run: |
        echo "Looking for version of '${{inputs.version-name}}'"
        version=$(awk -F'"' -v k="${{inputs.version-name}}" '$1 ~ "^"k"[[:space:]]*=" { print $2 }' gradle/libs.versions.toml)
        echo "Found version '$version'"

    - name: Save version
      shell: bash
      run: |
        echo "Saving version to GitHub output"
        echo "result=$version" >> $GITHUB_OUTPUT
