name: Configure Gradle
description: Configures Gradle for use in CI
inputs:
  working-directory:
    description: The directory in which to run the action
    default: .

runs:
  using: composite
  steps:
    - name: Configure custom Gradle distribution URL
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        
        ORIGINAL_URL=$(grep "distributionUrl" ./gradle/wrapper/gradle-wrapper.properties)
        echo "ORIGINAL_URL=$ORIGINAL_URL" >> $GITHUB_ENV
        
        GRADLE_VERSION=$(echo $ORIGINAL_URL | sed -n 's|.*gradle-\([0-9.]*\)-bin.zip|\1|p')
        CUSTOM_URL="https://d2pjps8lqszrgq.cloudfront.net/gradle-$GRADLE_VERSION-bin.zip"
        
        echo Configuring custom Gradle distribution URL with version: $GRADLE_VERSION
        echo Setting distribution URL to: $CUSTOM_URL
        
        # Detect OS and set appropriate sed option
        if sed --version 2>/dev/null | grep -q "GNU sed"; then
        SED_CMD="sed -i"  # GNU sed (Linux)
        else
        SED_CMD="sed -i ''"  # BSD sed (macOS)
        fi
        
        # Replace the line containing "distributionUrl" with the new distributionUrl
        $SED_CMD "/distributionUrl/c\\
        distributionUrl=$CUSTOM_URL\\
        " ./gradle/wrapper/gradle-wrapper.properties