name: Enable ProGuard
description: Enables ProGuard via local.properties

inputs:
  working-directory:
    description: The directory in which to run the action
    default: .

runs:
  using: composite
  steps:
    - name: Create local.properties
      working-directory: ${{inputs.working-directory}}
      shell: bash
      run: |
        echo "Creating local.properties"
        touch local.properties
        echo "Running ls:"
        ls

    - name: Enable ProGuard in local.properties
      working-directory: ${{inputs.working-directory}}
      shell: bash
      run: |
        echo "Writing to local.properties"
        echo "aws.sdk.proguard = true" > local.properties
        echo "File contents:"
        cat local.properties
