name: Depend on version
description: Updates a libs.versions.toml dependency

inputs:
  working-directory:
    description: The root directory of the project
    default: .
  dependency:
    description: The dependency to update
  version:
    description: The version to update the dependency to

runs:
  using: composite
  steps:
    - name: Update dependency
      working-directory: ${{inputs.working-directory}}
      shell: bash
      run: |
        echo "Updating depdendency '${{inputs.dependency}}' to '${{inputs.version}}'"
        sed -i "s/^${{ inputs.dependency }} = \".*\"/${{ inputs.dependency }} = \"${{ inputs.version }}\"/" gradle/libs.versions.toml
        
        echo "Printing first occurence of '${{inputs.dependency}}' in 'libs.versions.toml':"
        grep "${{inputs.dependency}}" gradle/libs.versions.toml | head -n 1
