name: Extract version from a file
description: Extracts the specified version from a file

inputs:
  working-directory:
    description: Directory in which the action will run
    default: .
  version-name:
    description: Name of the version to extract e.g. 'crt-kotlin-version'
  file-path:
    description: Path to the file to search for the version in (relative to `working-directory`).
  output-path:
    description: Directory where the version will be saved. The action writes the found version to 'version.txt' inside this directory
    default: .

runs:
  using: composite
  steps:
    - name: Extract version
      working-directory: ${{inputs.working-directory}}
      shell: bash
      run: |
        echo "Looking for version '${{inputs.version-name}}' in '${{inputs.file-path}}'"
        version=$(awk -F'=' -v k="${{inputs.version-name}}" '$1 ~ "^"k"[[:space:]]*" { gsub(/[[:space:]]*/, "", $2); gsub(/"/,"",$2); print $2 }' ${{inputs.file-path}})
        echo "Found version '$version'"
        
        echo "Saving version to '${{inputs.output-path}}/version.txt'"
        echo "$version" > ${{inputs.output-path}}/version.txt
