name: Calculate Artifact Size
description: Calculates size for JVM artifacts

inputs:
  upload:
    description: Whether the metrics should be uploaded to S3/Cloudwatch
  release_metrics:
    description: Whether the metrics are coming from a release build

runs:
  using: composite
  steps:
    - name: Calculate artifact sizes
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        IDENTIFIER: ${{ github.ref_name }}
        UPLOAD: ${{ inputs.upload }}
        RELEASE_METRICS: ${{ inputs.release_metrics }}
      run: |
        chmod +x ../utils/build-and-upload/main.sh
        ../utils/build-and-upload/main.sh
