name: Minor version bump
description: Verifies branch is ready to merge before minor version bump
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Gradle
      uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main

    - name: Verify minor version bump
      shell: bash
      run: |
        # Only continue on branches starting with vX.X (e.g. v1.2, v1.2.3, v1.2-main)
        if [[ ! "${{ github.head_ref }}" =~ ^v[0-9]+\.[0-9]+.*$ ]]; then
          exit 0
        fi
        
        ./gradlew verifyMinorVersionBump
