name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - 'feat-*'
  workflow_dispatch:

env:
  PACKAGE_NAME: aws-kotlin-repo-tools
  RUN: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  linux-compat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Configure Gradle
      uses: .github/actions/aws-kotlin-repo-tools-custom-gradle-distribution-url
    - name: Build and Test ${{ env.PACKAGE_NAME }}
      run: |
        ./gradlew build

  macos-compat:
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Configure Gradle
      uses: .github/actions/aws-kotlin-repo-tools-custom-gradle-distribution-url
    - name: Build and Test ${{ env.PACKAGE_NAME }}
      run: |
        ./gradlew build

  windows-compat:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Configure Gradle
        uses: .github/actions/aws-kotlin-repo-tools-custom-gradle-distribution-url
      - name: Build and Test ${{ env.PACKAGE_NAME }}
        run: |
          ./gradlew build