name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - 'feat-*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PACKAGE_NAME: aws-kotlin-repo-tools
  RUN: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  linux-compat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Configure JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
        cache: 'gradle'

    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Configure Gradle
      uses: ./.github/actions/configure-gradle
    - name: Build and Test ${{ env.PACKAGE_NAME }}
      run: |
        ./gradlew build

  macos-compat:
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Configure JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
        cache: 'gradle'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::934480575838:role/aws-sdk-kotlin-pr-github-oidc-role
        aws-region: us-west-2
    - name: Setup Kat
      uses: ./.github/actions/setup-kat

    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Configure Gradle
      uses: ./.github/actions/configure-gradle
    - name: Build and Test ${{ env.PACKAGE_NAME }}
      run: |
        ./gradlew build

  windows-compat:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::934480575838:role/aws-sdk-kotlin-pr-github-oidc-role
          aws-region: us-west-2
      - name: Setup Kat
        uses: ./.github/actions/setup-kat

      - name: Configure Gradle
        uses: ./.github/actions/configure-gradle
      - name: Build and Test ${{ env.PACKAGE_NAME }}
        run: |
          ./gradlew build
