name: Lint

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PACKAGE_NAME: aws-kotlin-repo-tools

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Configure Gradle
      uses: .github/actions/configure-gradle
    - name: Lint ${{ env.PACKAGE_NAME }}
      run: |
        ./gradlew ktlint
