name: Testing new GH action
on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Run GH action
        uses: ./.github/actions/sync-feature-branches
        with:
          disabled-feature-branches: 'test-main'